### ISSUE TITLE
error when generating path tree the second time

### ISSUE THREAD

**Issue by AzureViolin** [AzureViolin/intelligent_scissors_5421spring2018#6]
```bash
......generating path tree......
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.4/tkinter/__init__.py", line 1536, in __call__
    return self.func(*args)
  File "gui.py", line 462, in show_path_tree
    obj.path_tree_generation()
  File "/home/hao/HKUST/5421_spring_18/intelligent_scissors_5421spring2018/intelligent_scissor.py", line 160, in path_tree_generation
    self.path_tree = np.concatenate([self.path_tree, self.path_tree, np.zeros((self.height*3, self.width*3,1), dtype=np.uint8)],axis=2 )
ValueError: all the input arrays must have same number of dimensions
```

**Comment by AzureViolin** [comment]
reproduce this bug by first ctrl + click, open scissor window, choose path_tree or minimum_path, choose image_with_contour again, click somewhere else on the image, and choose path_tree or minimum_path again.
